/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alarm: typeof import('./src/components/icons/Alarm.vue')['default']
    Alert: typeof import('./src/components/icons/Alert.vue')['default']
    Alldown: typeof import('./src/components/icons/Alldown.vue')['default']
    Allup: typeof import('./src/components/icons/Allup.vue')['default']
    Annular: typeof import('./src/components/icons/Annular.vue')['default']
    Arrowdown: typeof import('./src/components/icons/Arrowdown.vue')['default']
    Auto: typeof import('./src/components/icons/Auto.vue')['default']
    CharsOperate: typeof import('./src/components/CharsOperate.vue')['default']
    Close: typeof import('./src/components/icons/Close.vue')['default']
    Controls: typeof import('./src/components/icons/Controls.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FrameInfo: typeof import('./src/components/frame-info.vue')['default']
    Full: typeof import('./src/components/icons/Full.vue')['default']
    Handle: typeof import('./src/components/icons/Handle.vue')['default']
    History: typeof import('./src/components/icons/History.vue')['default']
    Horizon: typeof import('./src/components/icons/Horizon.vue')['default']
    Lang: typeof import('./src/components/icons/Lang.vue')['default']
    Latest: typeof import('./src/components/icons/Latest.vue')['default']
    Maximize: typeof import('./src/components/icons/Maximize.vue')['default']
    Minimize: typeof import('./src/components/icons/Minimize.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    Position: typeof import('./src/components/icons/Position.vue')['default']
    Product: typeof import('./src/components/icons/Product.vue')['default']
    Reset: typeof import('./src/components/icons/Reset.vue')['default']
    Robot: typeof import('./src/components/icons/Robot.vue')['default']
    Rotate: typeof import('./src/components/icons/Rotate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Save: typeof import('./src/components/icons/Save.vue')['default']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
    Surveying: typeof import('./src/components/icons/Surveying.vue')['default']
    Unfold: typeof import('./src/components/icons/Unfold.vue')['default']
    Vertical: typeof import('./src/components/icons/Vertical.vue')['default']
  }
}
