/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Arrowdown: typeof import('./src/components/icons/Arrowdown.vue')['default']
    ClipPath: typeof import('./src/components/Clip-Path.vue')['default']
    Close: typeof import('./src/components/icons/Close.vue')['default']
    Controls: typeof import('./src/components/icons/Controls.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Horizon: typeof import('./src/components/icons/Horizon.vue')['default']
    Lang: typeof import('./src/components/icons/Lang.vue')['default']
    Maximize: typeof import('./src/components/icons/Maximize.vue')['default']
    Minimize: typeof import('./src/components/icons/Minimize.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
  }
}
