/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClipPath: typeof import('./src/components/Clip-Path.vue')['default']
    Close: typeof import('./src/components/icons/Close.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Maximize: typeof import('./src/components/icons/Maximize.vue')['default']
    Maxmize: typeof import('./src/components/icons/Maxmize.vue')['default']
    Minimize: typeof import('./src/components/icons/Minimize.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    S: typeof import('./src/components/s.vue')['default']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
  }
}
