/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function configureThreadPool(maxThreads: number): number

export declare function evaluateDirect(
  times: Float64Array,
  values: Float64Array,
  offsetDegrees: Float64Array,
  segmentOffsets: Uint32Array,
  durations: Float64Array,
  accelRatios: Float64Array,
  thetaMaxDegrees: number,
  numBins: number
): number

export declare function evaluateExpanded(
  times: Float64Array,
  values: Float64Array,
  offsetDegrees: Float64Array,
  segmentOffsets: Uint32Array,
  durations: Float64Array,
  accelRatios: Float64Array,
  thetaMaxDegrees: number,
  numBins: number
): number

export interface NativeSearchResult {
  theta: number
  loss: number
  evaluations: number
  sampleThetas: Array<number>
  sampleLosses: Array<number>
}

export declare function searchBestDirect(
  times: Float64Array,
  values: Float64Array,
  offsetDegrees: Float64Array,
  segmentOffsets: Uint32Array,
  durations: Float64Array,
  accelRatios: Float64Array,
  minDegrees: number,
  maxDegrees: number,
  stepDegrees: number,
  numBins: number
): NativeSearchResult

export declare function searchBestExpanded(
  times: Float64Array,
  values: Float64Array,
  offsetDegrees: Float64Array,
  segmentOffsets: Uint32Array,
  durations: Float64Array,
  accelRatios: Float64Array,
  minDegrees: number,
  maxDegrees: number,
  stepDegrees: number,
  numBins: number
): NativeSearchResult

export declare function solveBubbleBatch(
  rowPtr: Int32Array,
  colInd: Int32Array,
  values: Float64Array,
  targets: Float64Array,
  numBins: number,
  lambda: number,
  mu: number
): Array<number>
